### ISSUE TITLE
`-wipe` does not exit

### ISSUE THREAD

**Issue by b10n** [rvolosatovs/mooshy#40] opened 2018-04-17 10:15 UTC
Execution should resume after the wipe is finished.

**Comment by rvolosatovs** [comment] 2018-04-17 10:43
Yeah, so the problem is the same as with the usual `execution`. After closing the shell you should send 3 characters to resume execution.

**Comment by rvolosatovs** [comment] 2018-05-06 12:45
Closed by #41

**Closed** 2018-05-06 12:45 UTC
Labels: bug
